### ISSUE TITLE
Broken sites/stylesheets, PhantomJS version woes

### ISSUE THREAD

**Issue by veltman** [pastpages/pastpages.org#166]
The following sites seem consistently broken in a way that suggest unloaded stylesheets (and maybe more):

New York Times: http://www.pastpages.org/site/new-york-times/
Bloomberg: http://www.pastpages.org/site/bloomberg/
SVT: http://www.pastpages.org/site/svt/
Seattle Times: http://www.pastpages.org/site/seattle-times/
NPR: http://www.pastpages.org/site/npr/
Denver Post: http://www.pastpages.org/site/denver-post/
International New York Times: http://www.pastpages.org/site/international-nyt/

I'll investigate further when I have a chance but when I run `phantomjs archive/tasks/images.js` with PhantomJS v2.0.0 on these sites locally, they work fine, so a few initial thoughts about possible differences:

-The bundled phantom in PP is v1.8.1.  If I run the script with that version instead, I get all kinds of new errors.  In some cases, like the International NYT, it crashes without rendering at all.  The results don't match up exactly with what's on the PP site so I'm not sure this is the full explanation, but there's definitely a big discrepancy between the versions, so an upgrade might be worth a shot.

-Server IP - maybe certain resource servers have flagged the live PP server as an unwanted crawler? Seems unlikely but I guess it's possible.

**Comment by palewire** [comment]
Upgrading a great idea.
